[server]
headless = true
address = "0.0.0.0"
port = 8502

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#232323"
font = "sans serif"